---
name: Main
on: [push, pull_request]
permissions:
  contents: read
jobs:
  # We would never use usernetes on a single node
  #single-node:
  #  name: "Single node"
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      container_engine: [docker, nerdctl, podman]
  #  uses: ./.github/workflows/reusable-single-node.yaml
  #  with:
  #    container_engine: ${{ matrix.container_engine }}

  multi-node:
    name: "Multi node"
    strategy:
      fail-fast: false
      matrix:
        include:
          - lima_template: template://ubuntu-24.04
            container_engine: docker
          - lima_template: template://ubuntu-24.04
            container_engine: docker
            cni: calico
          - lima_template: template://ubuntu-24.04
            container_engine: docker
            container_engine_mode: rootful
          - lima_template: template://ubuntu-24.04
            container_engine: nerdctl
          - lima_template: template://centos-stream-9
            container_engine: podman
          - lima_template: template://fedora
            container_engine: podman
          - lima_template: template://experimental/fedora-rawhide
            container_engine: podman
          - lima_template: template://experimental/fedora-rawhide
            container_engine: podman
            cni: calico
    uses: ./.github/workflows/reusable-multi-node.yaml
    with:
      lima_template: ${{ matrix.lima_template }}
      container_engine: ${{ matrix.container_engine }}
      container_engine_mode: ${{ matrix.container_engine_mode }}
      cni: ${{ matrix.cni }}

  k8s-in-k8s:
    name: "Kubernetes-in-Kubernetes"
    uses: ./.github/workflows/reusable-k8s-in-k8s.yaml
